# Description: Parameters for the legacy process_cloud_node real-robot full-mission profile.
/**:
  ros__parameters:
    ground_class_label: 0
    car_class_label: 1
    tree_trunk_class_label: 8
    light_pole_class_label: 9
    desired_acc_obj_pub_rate: 1.0
    valid_range_threshold: 6.5
    epsilon_scan: 0.5
    min_samples_scan: 200
    depth_percentile_lower: 15
    depth_percentile_uppper: 40
    confidence_threshold: 0.4
    cuboid_length_cutoff_upper: 1.0
    cuboid_width_cutoff_upper: 1.0
    cuboid_height_cutoff_upper: 5.0
    assignment_threshold: 0.8
    downsample_res: 0.1
    num_instance_point_lim: 30000
    for_forestry_bags: false
    sim: false
    ########### THREE PARAMS ARE LINKED TOGETHER ###########
    expected_segmentation_rate: 10
    time_to_initialize_cuboid: 0.2
    time_to_delete_lost_track_cuboid: 5
    ########################################################
